[buildPlans.iosevka-code]
family = "Iosevka Code"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-code.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothed-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "curly-tailed"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-serifless"
h = "straight-serifless"
i = "serifed"
j = "serifed"
k = "straight-serifless"
l = "serifed-semi-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifed"
s = "serifless"
t = "bent-hook"
u = "toothed-serifless"
v = "straight-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
zero = "tall-slashed"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "semi-open"
five = "upright-arched"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-high"
underscore = "high"
caret = "medium"
paren = "normal"
brace = "straight"
guillemet = "curly"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "through"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.iosevka-code.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-code.weights.retina]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-code.widths.normal]
shape = 600
menu = 5
css = "normal"